tap "charmbracelet/tap"
tap "codeclimate/formulae"
tap "derailed/k9s"
tap "derailed/popeye"
tap "fairwindsops/tap"
tap "farmotive/k8s"
tap "getsentry/tools"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "instrumenta/instrumenta"
tap "neovim/neovim"
tap "reviewdog/tap"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"
tap "versent/taps"
tap "wagoodman/dive"
tap "wata727/tflint"
tap "weaveworks/tap"
brew "ack"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "readline"
brew "asdf"
brew "autojump"
brew "awscli"
brew "bash"
brew "bat"
brew "libpng"
brew "gettext"
brew "curl"
brew "direnv"
brew "docker-completion"
brew "docker-compose-completion"
brew "editorconfig"
brew "fd"
brew "jpeg"
brew "ffmpeg"
brew "fish"
brew "fluxctl"
brew "fx"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-tar"
brew "go"
brew "hadolint"
brew "helmfile"
brew "highlight"
brew "ncurses"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "krew"
brew "kubectx"
brew "kubeseal"
brew "kubespy"
brew "kustomize"
brew "libsodium"
brew "libtermkey"
brew "libuv"
brew "libxml2"
brew "libxslt"
brew "lsd"
brew "mas"
brew "mitmproxy"
brew "mycli"
brew "ncdu"
brew "neovim"
brew "nyancat"
brew "octant"
brew "packer-completion"
brew "pgcli"
brew "postgresql", restart_service: true
brew "prettyping"
brew "pwgen"
brew "rcm"
brew "ripgrep"
brew "ssh-copy-id"
brew "starship"
brew "stern"
brew "terminal-notifier"
brew "tflint"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "charmbracelet/tap/glow"
brew "derailed/k9s/k9s"
brew "derailed/popeye/popeye"
brew "fairwindsops/tap/polaris"
brew "farmotive/k8s/kpoof", args: ["without-kubernetes-cli"]
brew "getsentry/tools/sentry-cli"
brew "hashicorp/tap/terraform-ls"
brew "instrumenta/instrumenta/kubeval"
brew "thoughtbot/formulae/gitsh"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD", "with-jansson"]
brew "versent/taps/saml2aws"
brew "wagoodman/dive/dive"
brew "weaveworks/tap/eksctl"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "aws-vault"
cask "backblaze"
cask "bartender"
cask "battle-net"
cask "coderunner"
cask "colorpicker-skalacolor"
cask "dash"
cask "deckset"
cask "discord"
cask "docker-edge"
cask "fantastical"
cask "firefox"
cask "firefox-developer-edition"
cask "font-victormono-nerd-font"
cask "github"
cask "gitkraken"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite-no-mail"
cask "iina"
cask "imageoptim"
cask "kitty"
cask "lens"
cask "microsoft-teams"
cask "monitorcontrol"
cask "ngrok"
cask "omnioutliner"
cask "paw"
cask "pgadmin4"
cask "plex"
cask "postbox"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "resilio-sync"
cask "safari-technology-preview"
cask "screens"
cask "signal"
cask "sketch"
cask "skype"
cask "slack-beta"
cask "suspicious-package"
cask "syntax-highlight"
cask "transmit"
cask "tuple"
cask "visual-studio-code"
cask "whatsapp"
mas "1Blocker", id: 1107421413
mas "CARROT Weather", id: 993487541
mas "Deliveries", id: 924726344
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "Jira", id: 1475897096
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Outbank", id: 1094255754
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "Reeder", id: 1529448980
mas "Save to Pocket", id: 1477385213
mas "Speedtest", id: 1153157709
mas "StopTheMadness", id: 1376402589
mas "Tab Suspender", id: 1495356253
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Vimari", id: 1480933944
