return {
  -- {
  --   "nvim-neo-tree/neo-tree.nvim",
  --   cmd = "Neotree",
  --   keys = {
  --     { "<leader>N", "<cmd>Neotree reveal<cr>", desc = "Reveal File in Neotree" },
  --     { "<leader>n", "<cmd>Neotree toggle<cr>", desc = "Toggle Neotree" },
  --   },
  --   init = function()
  --     vim.g.neo_tree_remove_legacy_commands = 1
  --     if vim.fn.argc() == 1 then
  --       local stat = vim.loop.fs_stat(vim.fn.argv(0))
  --       if stat and stat.type == "directory" then
  --         require("neo-tree")
  --       end
  --     end
  --   end,
  --   opts = {
  --     close_if_last_window = true,
  --     filesystem = {
  --       follow_current_file = true,
  --     },
  --   },
  -- },
}
