command_timeout = 1000
[aws]

disabled = false
symbol = "☁ "

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"arn:aws:eks:.*:cluster/(?P<var_cluster>.*)" = "$var_cluster"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[git_branch]
symbol = " "

[gcloud]
disabled = true

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[elixir]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "
