command_timeout = 2000
[aws]

disabled = false
symbol = "󰸏 "

[kubernetes]
disabled = false

[[kubernetes.contexts]]

context_pattern = "arn:aws:eks:.*:cluster/(?P<var_cluster>.*)"
context_alias = "$var_cluster"

[battery]
# disabled = false
# full_symbol = "󰁹"
# charging_symbol = "󰂄"
# discharging_symbol = "󰂌"

[conda]
symbol = " "

[git_branch]
symbol = " "

[gcloud]
disabled = true

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[elixir]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "
