gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - reverse
git:
  log:
    order: default
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
keybinding:
  universal:
    # quit: '<ctrl+c>'
    # quit-alt1: '<ctrl+c>'
    prevBlock: 'K'
    nextBlock: 'J'
  commits:
    moveDownCommit: '<ctrl+d>'
    moveUpCommit: '<ctrl+u>'
