gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - reverse
git:
  log:
    order: default
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  universal:
    quit: '<c-c>'
    quit-alt1: '<c-c>'
    prevBlock: 'K'
    nextBlock: 'J'
  commits:
    moveDownCommit: '<c-d>'
    moveUpCommit: '<c-u>'
