lastupdatecheck: 0
recentrepos:
- /Users/alexander/.dotfiles
- /Users/alexander/projects/remote/employ/tiger
- /Users/alexander/projects/remote/employ/dragon
- /Users/alexander/projects/remote/rfcs
- /Users/alexander/projects/remote/devops/infra-live
- /Users/alexander/projects/remote/remoteoss/hammer-backend-redis
- /Users/alexander/projects/spandex_phoenix
- /Users/alexander/projects/spandex
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
