[tools]
node = "22.14.0"
yarn = "1.22.19"
postgres = "14.15"
erlang = "27.2.4"
elixir = "1.18.2-otp-27"
remotectl = "latest"
rust = "nightly"
ruby = "3.4.1"
neovim = "0.11"
rebar = "3.24.0"

[settings]
experimental = true
