[tools]
node = "22.18.0"
yarn = "1.22.22"
postgres = "17.7"
erlang = "27.3.4"
elixir = "1.20.3-otp-27"
remotectl = "latest"
rust = "1.96"
ruby = "3.4.1"
neovim = "0.12.3"
rebar = { version = "3.27", asset_pattern = "rebar3" }
dexter = "latest"
remotecli = "latest"
# dexter = "latest"
# claude = "2.1.112"

[settings]
experimental = true
