[tools]
node = "18.18.2"
yarn = "1.22.19"
postgres = "14.9"
erlang = "27.2"
elixir = "1.18.2-otp-27"
remotectl = "latest"
rust = "nightly"
ruby = "3.4.1"
neovim = "nightly"
rebar = "3.24.0"

[settings]
experimental = true
